version: '3'

services:
  # server:
  #   container_name: zephyr-server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.server
  #   env_file: .env
  #   # restart: always
  #   ports:
  #     - '${PORT}:${PORT}'
  #   depends_on:
  #     - mysql
  postgres:
    env_file: .env
    container_name: zephyr-db
    image: postgres
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_DB: ${DEV_DB_DATABASE}
    ports:
      - '${DEV_DB_PORT}:${DEV_DB_PORT}'
  # mysql:
  #   env_file: .env
  #   container_name: zephyr-db
  #   image: mysql:8
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
  #     MYSQL_DATABASE: ${DEV_DB_DATABASE}
  #   ports:
  #     - '${DEV_DB_PORT}:${DEV_DB_PORT}'
