# not in use

FROM node:13-alpine as BUILD

RUN mkdir -p /app/.cache/yarn && chmod 777 /app/.cache/yarn
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

ENV HOME=/app
WORKDIR $HOME

COPY ./server .
COPY ./shared ./src/shared

RUN yarn build


FROM node:13-alpine

ENV HOME=/app
WORKDIR $HOME

COPY --from=BUILD ./app/dist .

EXPOSE ${WEB_PORT}

USER node
