FROM node:13-alpine

# TODO add server docker config.

# RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

# ENV HOME=/app

# WORKDIR $HOME

# COPY . .

# EXPOSE ${PORT}

# RUN ls

# RUN yarn run init

# USER node

# ENTRYPOINT ["ts-node"]

# CMD ["index.ts"]
